url: https://simulatine.github.io/100DaysOfCode
theme: minima


# Site author information
site.author.name: Simulatine
site.author.email: simulatine@gmail.com

header_pages:
    - index.md
    - about.md
    
# Social media links. The Minima theme will automatically show
# these at the bottom of each page.
minima:
  social:
    twitter: simulatine

minima:
  skin: dark
