title: Simulatine's 100 Days Of Code
# Use the minima theme
theme: minima

# Site author information
author:
  name: Simulatine
  email: simulatine@gmail.com

minima:
  date_format: "%A, %-d %b, %Y"

  # List of social media links in the footer
  social_links:
    twitter: simulatine

plugins:
  - jekyll-feed
  - jekyll-seo-tag