title: Simulatine's 100 Days Of Code
# Site author information
author:
  name: Simulatine
  email: simulatine@gmail.com
description: Learning and having fun with code. Python, Pygame, simulations.

# Use the minima theme
theme: minima

minima:
  date_format: "%A, %-d %b, %Y"

  # List of social media links in the footer
  social_links:
    twitter: simulatine

header_pages:
  - index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag